<a href="https://colab.research.google.com/github/unica-isde/isde/blob/master/notebooks/lab01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Basics

This notebook includes some examples from this lecture: https://github.com/unica-isde/isde/blob/master/slides/03-Python.pdf 

In [1]:
# welcome
print("Hello world!")

Hello world!


In [2]:
x = 34 - 23
y = "Hello"
z = 3.45

if z == 3.45 or y=="Hello": 
    x = x + 1
    y = y + " World"

print("x: ", x)
print("y: ", y)

12
Hello World


## Lists

Modify mutable objects with in-place operators...

In [5]:
x = [1, 2, 3]
y = x
x.append(4)  # this modifies both lists 
print("x: ", x)
print("y: ", y)

x:  [1, 2, 3, 4]
y:  [1, 2, 3, 4]


... and avoid the issue by copying the object first.

In [4]:
x = [1, 2, 3]
y = x[:]  #  copy the whole list in memory
x.append(4)
print("x: ", x)
print("y: ", y)

x:  [1, 2, 3, 4]
y:  [1, 2, 3]


Other operations with lists.

In [6]:
l = list(range(0,5))
print(l)

l = list(range(-10,-20,-1))
print(l)

[0, 1, 2, 3, 4]
[-10, -11, -12, -13, -14, -15, -16, -17, -18, -19]


## Control of flow

Examples of ```for``` loops.

In [8]:
a = ['a', 'b', 'c']

for elem in a:
    print(elem)

print(" ")

for i, elem in enumerate(a):
    print(i, elem)

print(" ")

for i in range(len(a)):
    print(i, a[i])

a
b
c
 
0 a
1 b
2 c
 
0 a
1 b
2 c


## Numpy arrays

Some examples of indexing.

In [14]:
import numpy as np

a = np.eye(3)
print("Identity matrix: ", a)
print(" ")

idx = np.array([1, 1, 0])  # extract first and second row (idx==1)
print("Rows to be extracted: ", idx)
print("... when idx==1: ", idx == 1)
print(" ")

print("Indexing with a Boolean vector:\n", a[idx==1, :])
print(" ")

r = [0,1]  # extract rows with index 0 and 1
print("Indexing with a list of indices:\n", a[r,:])
print(" ")

Identity matrix:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
Rows to be extracted:  [1 1 0]
... when idx==1:  [ True  True False]
 
Indexing with a Boolean vector:
 [[1. 0. 0.]
 [0. 1. 0.]]
 
Indexing with a list of indices:
 [[1. 0. 0.]
 [0. 1. 0.]]
 
