<a href="https://colab.research.google.com/github/unica-isde/isde/blob/master/notebooks/lab01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Basics


In [2]:
# welcome
print("Hello world!")

x = [1, 2, 3]
y = x
x.append(4)
print("x: ", x)
print("y: ", y)


Hello world!
x:  [1, 2, 3, 4]
y:  [1, 2, 3, 4]


In [3]:
x = [1, 2, 3]
y = x[:]  #  copy the whole list in memory
x.append(4)
print("x: ", x)
print("y: ", y)

x:  [1, 2, 3, 4]
y:  [1, 2, 3]


In [8]:
l = list(range(0,5))
print(l)

l = list(range(-10,-20,-1))
print(l)

[0, 1, 2, 3, 4]
[-10, -11, -12, -13, -14, -15, -16, -17, -18, -19]


In [13]:
a = ['pippo', 'paperino', 'topolino']

for elem in a:
    print(elem)

for i, elem in enumerate(a):
    print(i, elem)

for i in range(len(a)):
    print(i, a[i])

pippo
paperino
topolino
0 pippo
1 paperino
2 topolino
0 pippo
1 paperino
2 topolino


In [21]:
import numpy as np

a = np.eye(3)
print(a)

idx = np.array([1, 1, 0])

print(idx)
print(idx == 1)

print(a[idx==1, :])

r = [0,1]
print(a[r,:])


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 1 0]
[ True  True False]
[[1. 0. 0.]
 [0. 1. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]]
